BENCH-301: Changed Product.Request categories to category
AnswerConsulting/AnswerKingAPI pull request #10
Opened 2023-01-12 17:06 UTC by bethcryer

2023-01-16 10:00 UTC, AudriusPutys approved these changes

2023-01-17 14:45 UTC, milkshakeuk requested changes

2023-01-17 14:45 UTC, milkshakeuk commented on AnswerKingAPI.yml
> +        category:
`categoryId`

2023-01-19 14:16 UTC, oleksiiRybak approved these changes

2023-01-19 15:00 UTC, merged